---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: cleanup
spec:
  description: >-
    This task will clean up a workspace by deleting all of the files.
  workspaces:
    - name: source
  steps:
    - name: cleanup
      image: alpine:3
      env:
        - name: WORKSPACE_SOURCE_PATH
          value: $(workspaces.source.path)
      command: ["/bin/sh", "-c"]
      args:
        - |-
          set -eu
          echo "Removing all files from workspace..."
          if [ -d "$WORKSPACE_SOURCE_PATH" ] ; then
            rm -rf "$WORKSPACE_SOURCE_PATH"/*
            rm -rf "$WORKSPACE_SOURCE_PATH"/.[!.]*
            rm -rf "$WORKSPACE_SOURCE_PATH"/..?*
          fi
          echo "All files deleted from workspace path: $WORKSPACE_SOURCE_PATH"

---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: nose
spec:
  description: >-
    This task will run nosetests on the provided application with nose,
    spec, and coverage plugins.
  workspaces:
    - name: source
  params:
    - name: args
      description: Arguments to pass to nose
      type: string
      default: "-v --with-spec --spec-color --with-coverage --cover-package=app"
    - name: database_uri
      description: Database connection string
      type: string
      default: "sqlite:///test.db"
  steps:
    - name: nosetests
      image: python:3.9-slim
      workingDir: $(workspaces.source.path)
      env:
        - name: DATABASE_URI
          value: $(params.database_uri)
      command: ["/bin/bash", "-c"]
      args:
        - |-
          pip install --upgrade pip && \
          pip install -qr requirements.txt && \
          nosetests $(params.args)

---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: flake8
spec:
  description: >-
    This task will run flake8 on the provided application source code.
  workspaces:
    - name: source
  params:
    - name: image
      description: The container image to use for running flake8
      type: string
      default: "python:3.9-slim"
    - name: args
      description: Arguments to pass to flake8
      type: array
      default: ["--count", "--max-complexity=10", "--max-line-length=127", "--statistics"]
  steps:
    - name: flake8
      image: $(params.image)
      workingDir: $(workspaces.source.path)
      command: ["/bin/bash", "-c"]
      args:
        - |-
          pip install flake8 --quiet && \
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics && \
          flake8 . $(params.args)

